import * as crypto from 'crypto';
import * as fs from 'fs/promises';
import * as http from 'http';
import * as path from 'path';
import * as vscode from 'vscode';
import { HookEvent, parseHookPayload, pickFolder } from '../../core/hooks/events';
import { atomicWrite, processAlive, readJson } from '../../core/store';
import { log } from '../env';

/**
 * Local receiver for agent hooks (Claude Code `type: "http"` hooks).
 *
 *  - Started lazily (only when hooks are installed / `autoStart: whenAgentDetected`), never for
 *    users who do not use hooks. ONE window per machine owns the fixed port
 *    (`changekeeper.hooks.port`); the others watch an inbox and take the port over when the owner goes.
 *  - Every window registers its folders in `<globalStorage>/hooks/windows/<pid>.json` (heartbeat
 *    every minute; a registration without heartbeat for 10 min, or whose pid is dead, is dropped).
 *  - The owner routes each event to EVERY window/folder that contains the file/cwd (each guard
 *    decides): itself directly, others through `<globalStorage>/hooks/inbox/<pid>/<id>.json` (polled every 1.5 s).
 *  - Requests must carry the per-user token (`X-CK-Token`, created once in `<globalStorage>/hooks/token`,
 *    mode 0600, exclusive create so concurrent windows agree on one value; the owner re-reads the file
 *    when a token does not match, so a token regenerated by another window is accepted); the custom
 *    header also forces a CORS preflight, so a web page cannot post to us. Bind is 127.0.0.1 only.
 *  - Nothing is ever answered with content: 204, so a hook can never inject context into the agent.
 */
export interface WindowRegistration {
  pid: number;
  folders: string[];
  since: string;
  /** last heartbeat (ISO) */
  beat?: string;
  /** this window owns the port right now */
  owner?: boolean;
}

export const DEFAULT_HOOK_PORT = 47391;
const HEARTBEAT_MS = 60_000;
const STALE_MS = 10 * 60_000;
const INBOX_MS = 1500;
const OWNER_CHECK_EVERY = 3; // inbox ticks

export class HookServer implements vscode.Disposable {
  private server: http.Server | undefined;
  private owner = false;
  private binding = false;
  private started = false;
  private retry: ReturnType<typeof setTimeout> | undefined;
  private inboxTimer: ReturnType<typeof setInterval> | undefined;
  private beatTimer: ReturnType<typeof setInterval> | undefined;
  private startPromise: Promise<void> | undefined;
  private tick = 0;
  private tokenValue: string | undefined;
  private tokenReloadedAt = 0;
  private folders: string[] = [];
  private since = new Date().toISOString();
  private lastEventAt: string | undefined;
  private eventsSeen = 0;
  private readonly _onEvent = new vscode.EventEmitter<{ folder: string; event: HookEvent }>();
  readonly onEvent = this._onEvent.event;
  private disposed = false;

  /** `pid` is only overridden by the unit tests (two instances in one process must look like two windows). */
  constructor(private readonly storageRoot: string, port: number, private readonly pid: number = process.pid) {
    this.port = HookServer.validPort(port);
  }
  private port: number;

  /** A usable TCP port (integer 1024–65535); anything else falls back to the default (and is logged by the caller). */
  static validPort(p: unknown): number {
    return typeof p === 'number' && Number.isInteger(p) && p >= 1024 && p <= 65535 ? p : DEFAULT_HOOK_PORT;
  }

  get root(): string {
    return path.join(this.storageRoot, 'hooks');
  }
  get isOwner(): boolean {
    return this.owner;
  }
  get isStarted(): boolean {
    return this.started;
  }
  get currentPort(): number {
    return this.port;
  }
  get status(): { started: boolean; owner: boolean; port: number; lastEventAt?: string; events: number } {
    return { started: this.started, owner: this.owner, port: this.port, lastEventAt: this.lastEventAt, events: this.eventsSeen };
  }

  private get tokenFile(): string {
    return path.join(this.root, 'token');
  }

  /** The per-user token (created once, exclusively, so windows starting together agree on one value). */
  async token(): Promise<string> {
    if (this.tokenValue) return this.tokenValue;
    for (let attempt = 0; attempt < 5; attempt++) {
      const t = (await fs.readFile(this.tokenFile, 'utf8').catch(() => '')).trim();
      if (/^[a-f0-9]{48}$/.test(t)) {
        this.tokenValue = t;
        return t;
      }
      const fresh = crypto.randomBytes(24).toString('hex');
      try {
        await fs.mkdir(this.root, { recursive: true });
        await fs.writeFile(this.tokenFile, fresh, { flag: 'wx', mode: 0o600 });
        this.tokenValue = fresh;
        return fresh;
      } catch (e: any) {
        if (e && e.code === 'EEXIST') {
          // someone else created it a moment ago; if it is malformed (user edited it) replace it once
          const again = (await fs.readFile(this.tokenFile, 'utf8').catch(() => '')).trim();
          if (/^[a-f0-9]{48}$/.test(again)) {
            this.tokenValue = again;
            return again;
          }
          await atomicWrite(this.tokenFile, fresh, { mode: 0o600 });
          this.tokenValue = fresh;
          return fresh;
        }
        throw e;
      }
    }
    throw new Error('could not create the hook token');
  }

  /** The token as stored on disk, WITHOUT creating one (used to decide whether we should start at all). */
  async peekToken(): Promise<string | undefined> {
    if (this.tokenValue) return this.tokenValue;
    const t = (await fs.readFile(this.tokenFile, 'utf8').catch(() => '')).trim();
    return /^[a-f0-9]{48}$/.test(t) ? t : undefined;
  }

  /** Re-reads the token file (throttled) so a token regenerated by another window is honoured by the owner. */
  private async reloadToken(): Promise<string | undefined> {
    const now = Date.now();
    if (now - this.tokenReloadedAt < 2000) return this.tokenValue;
    this.tokenReloadedAt = now;
    const t = (await fs.readFile(this.tokenFile, 'utf8').catch(() => '')).trim();
    if (/^[a-f0-9]{48}$/.test(t)) this.tokenValue = t;
    return this.tokenValue;
  }

  async start(folders: string[]): Promise<void> {
    if (this.disposed || this.started) {
      if (this.started) await this.setFolders(folders);
      return;
    }
    this.started = true;
    this.folders = folders;
    this.since = new Date().toISOString();
    // `stop()`/`dispose()` may land while we are still setting up: they await this promise, and every
    // step re-checks `started` so a cancelled start never leaves a timer or a listener behind.
    this.startPromise = (async () => {
      await fs.mkdir(path.join(this.root, 'windows'), { recursive: true });
      await fs.mkdir(this.inboxDir, { recursive: true });
      await this.token();
      if (!this.started) return;
      await this.register();
      if (!this.started) return;
      await this.tryBind();
      if (!this.started) {
        await this.closeServer();
        return;
      }
      if (!this.inboxTimer) this.inboxTimer = setInterval(() => void this.onTick(), INBOX_MS);
      if (!this.beatTimer) this.beatTimer = setInterval(() => void this.register().catch(() => undefined), HEARTBEAT_MS);
    })();
    try {
      await this.startPromise;
    } finally {
      this.startPromise = undefined;
    }
  }

  /** Stops the receiver (port released, registration removed); `start()` may be called again later. */
  async stop(): Promise<void> {
    if (!this.started) return;
    this.started = false;
    // a start still running sees `started === false` and bails out; wait for it so nothing survives us
    await this.startPromise?.catch(() => undefined);
    if (this.retry) clearTimeout(this.retry);
    this.retry = undefined;
    if (this.inboxTimer) clearInterval(this.inboxTimer);
    if (this.beatTimer) clearInterval(this.beatTimer);
    this.inboxTimer = undefined;
    this.beatTimer = undefined;
    await this.closeServer();
    await fs.rm(path.join(this.root, 'windows', `${this.pid}.json`), { force: true }).catch(() => undefined);
    await fs.rm(this.inboxDir, { recursive: true, force: true }).catch(() => undefined);
  }

  async setFolders(folders: string[]): Promise<void> {
    this.folders = folders;
    if (this.started) await this.register();
  }

  async setPort(port: number): Promise<void> {
    const p = HookServer.validPort(port);
    if (p === this.port) return;
    this.port = p;
    if (this.retry) clearTimeout(this.retry);
    this.retry = undefined;
    if (!this.started) return;
    await this.closeServer();
    await this.tryBind();
  }

  private get inboxDir(): string {
    return path.join(this.root, 'inbox', String(this.pid));
  }

  private async register(): Promise<void> {
    if (!this.started) return;
    const reg: WindowRegistration = { pid: this.pid, folders: this.folders, since: this.since, beat: new Date().toISOString(), owner: this.owner };
    await atomicWrite(path.join(this.root, 'windows', `${this.pid}.json`), JSON.stringify(reg));
  }

  private async tryBind(): Promise<void> {
    if (this.disposed || !this.started || this.server || this.binding) return;
    this.binding = true;
    const server = http.createServer((req, res) => void this.handle(req, res));
    let settled = false;
    const done = await new Promise<'ok' | 'inuse' | 'error'>((resolve) => {
      const finish = (r: 'ok' | 'inuse' | 'error') => {
        if (settled) return;
        settled = true;
        resolve(r);
      };
      server.on('error', (e: any) => {
        if (!settled) {
          finish(e && e.code === 'EADDRINUSE' ? 'inuse' : 'error');
          if (!(e && e.code === 'EADDRINUSE')) log(`hook server error: ${String(e)}`);
          return;
        }
        // error after listening (rare): drop the server and try again later
        log(`hook server error: ${String(e)}`);
        if (this.server === server) {
          this.server = undefined;
          this.owner = false;
          void this.register().catch(() => undefined);
          this.scheduleRetry();
        }
      });
      try {
        server.listen(this.port, '127.0.0.1', () => finish('ok'));
      } catch (e) {
        log(`hook server cannot listen on ${this.port}: ${String(e)}`);
        finish('error');
      }
    });
    this.binding = false;
    if (done === 'ok') {
      if (this.disposed || !this.started) {
        server.close();
        return;
      }
      this.owner = true;
      this.server = server;
      if (this.retry) clearTimeout(this.retry);
      this.retry = undefined;
      log(`hook server listening on 127.0.0.1:${this.port} (this window owns the port)`);
      await this.register().catch(() => undefined);
      return;
    }
    try {
      server.close();
    } catch {
      /* not listening */
    }
    this.owner = false;
    if (done === 'inuse') this.scheduleRetry();
  }

  private scheduleRetry(): void {
    if (this.retry || this.disposed || !this.started) return;
    this.retry = setTimeout(() => {
      this.retry = undefined;
      void this.tryBind();
    }, 30_000);
  }

  private tokenMatches(given: string | string[] | undefined, expected: string | undefined): boolean {
    if (typeof given !== 'string' || !expected || given.length !== expected.length) return false;
    return crypto.timingSafeEqual(Buffer.from(given, 'utf8'), Buffer.from(expected, 'utf8'));
  }

  private async handle(req: http.IncomingMessage, res: http.ServerResponse): Promise<void> {
    try {
      if (req.method === 'OPTIONS') {
        // no CORS headers on purpose: browsers cannot use us
        res.writeHead(403).end();
        return;
      }
      if (req.method !== 'POST' || !(req.url ?? '').startsWith('/hook')) {
        res.writeHead(404).end();
        return;
      }
      const token = req.headers['x-ck-token'];
      let ok = this.tokenMatches(token, await this.token());
      if (!ok) ok = this.tokenMatches(token, await this.reloadToken());
      if (!ok) {
        res.writeHead(401).end();
        return;
      }
      const raw = await this.readBody(req);
      if (raw === 'too-large') {
        // answer, then keep draining what is still coming: closing the socket mid-upload makes the
        // sender fail with EPIPE (seen on macOS CI). A hard close only if it never stops.
        res.writeHead(413).end();
        const kill = setTimeout(() => req.destroy(), 2000);
        kill.unref?.();
        req.once('end', () => clearTimeout(kill));
        req.once('close', () => clearTimeout(kill));
        return;
      }
      if (raw === 'error') {
        res.writeHead(400).end();
        return;
      }
      let body: unknown;
      try {
        body = JSON.parse(raw.toString('utf8') || '{}');
      } catch {
        res.writeHead(400).end();
        return;
      }
      res.writeHead(204).end();
      const evt = parseHookPayload(body);
      if (evt) await this.route(evt);
    } catch (e) {
      log(`hook request failed: ${String(e)}`);
      try {
        res.writeHead(500).end();
      } catch {
        /* closed */
      }
    }
  }

  /** Reads the body up to 512 KB (event listeners, not for-await: leaving the loop early would destroy the socket before the answer is out). */
  private readBody(req: http.IncomingMessage): Promise<Buffer | 'too-large' | 'error'> {
    return new Promise((resolve) => {
      const chunks: Buffer[] = [];
      let size = 0;
      let done = false;
      req.on('data', (c: Buffer) => {
        if (done) return; // over the limit: keep draining, keep nothing
        size += c.length;
        if (size > 512 * 1024) {
          done = true;
          resolve('too-large');
          return;
        }
        chunks.push(c);
      });
      req.once('end', () => {
        if (done) return;
        done = true;
        resolve(Buffer.concat(chunks));
      });
      req.once('error', () => {
        if (done) return;
        done = true;
        resolve('error');
      });
    });
  }

  /** Owner-side routing: to every window/folder containing the path — ourselves directly, others through their inbox. */
  private async route(evt: HookEvent): Promise<void> {
    const probe = evt.filePath ?? evt.cwd;
    if (!probe) return;
    const windows = await this.liveWindows();
    let delivered = false;
    for (const w of windows) {
      for (const folder of w.folders) {
        if (!pickFolder(probe, [folder])) continue;
        delivered = true;
        if (w.pid === this.pid) {
          this.eventsSeen++;
          this.lastEventAt = new Date().toISOString();
          this._onEvent.fire({ folder, event: evt });
          continue;
        }
        const file = path.join(this.root, 'inbox', String(w.pid), `${Date.now()}-${crypto.randomBytes(3).toString('hex')}.json`);
        await atomicWrite(file, JSON.stringify({ folder, event: evt })).catch((e) => log(`hook inbox write failed: ${String(e)}`));
      }
    }
    if (!delivered) log(`hook event for ${probe} matched no open folder`);
  }

  /** For the doctor: does another live window own the port? */
  async liveOwnerElsewhere(): Promise<boolean> {
    return (await this.liveWindows()).some((w) => w.owner && w.pid !== this.pid);
  }

  /** Registrations of windows that are alive (dead pid or stale heartbeat → registration and inbox removed). */
  private async liveWindows(): Promise<WindowRegistration[]> {
    const dir = path.join(this.root, 'windows');
    let names: string[] = [];
    try {
      names = await fs.readdir(dir);
    } catch {
      return [];
    }
    const out: WindowRegistration[] = [];
    const now = Date.now();
    for (const n of names) {
      if (!n.endsWith('.json')) continue;
      const reg = await readJson<WindowRegistration>(path.join(dir, n));
      if (!reg || typeof reg.pid !== 'number' || !Number.isInteger(reg.pid) || !Array.isArray(reg.folders)) continue;
      if (reg.pid !== this.pid) {
        const beat = reg.beat ? Date.parse(reg.beat) : NaN;
        const stale = Number.isFinite(beat) && now - beat > STALE_MS;
        if (!processAlive(reg.pid) || stale) {
          // dead window (or a reused pid): clean its registration and inbox
          await fs.rm(path.join(dir, n), { force: true }).catch(() => undefined);
          await fs.rm(path.join(this.root, 'inbox', String(reg.pid)), { recursive: true, force: true }).catch(() => undefined);
          continue;
        }
      }
      out.push(reg);
    }
    return out;
  }

  private async onTick(): Promise<void> {
    if (!this.started) return;
    await this.drainInbox();
    this.tick++;
    // not the owner: if no live window owns the port any more, take it over now (not in 30 s)
    if (!this.owner && !this.server && !this.binding && this.tick % OWNER_CHECK_EVERY === 0) {
      const windows = await this.liveWindows();
      if (!windows.some((w) => w.owner && w.pid !== this.pid)) {
        if (this.retry) clearTimeout(this.retry);
        this.retry = undefined;
        await this.tryBind();
      }
    }
  }

  private async drainInbox(): Promise<void> {
    const dir = this.inboxDir;
    let names: string[] = [];
    try {
      names = (await fs.readdir(dir)).filter((n) => n.endsWith('.json')).sort();
    } catch {
      return;
    }
    for (const n of names) {
      const file = path.join(dir, n);
      const item = await readJson<{ folder: string; event: HookEvent }>(file);
      await fs.rm(file, { force: true }).catch(() => undefined);
      if (item && item.event && typeof item.folder === 'string') {
        this.eventsSeen++;
        this.lastEventAt = new Date().toISOString();
        this._onEvent.fire(item);
      }
    }
  }

  private async closeServer(): Promise<void> {
    const s = this.server;
    this.server = undefined;
    this.owner = false;
    if (s) await new Promise<void>((r) => s.close(() => r()));
  }

  async dispose(): Promise<void> {
    this.disposed = true;
    await this.stop();
    this._onEvent.dispose();
  }
}
