import { counters, FileChange, isFileReviewed, Session } from './session';

/**
 * Session report (Markdown) and a commit-message proposal. Pure, offline, no model involved.
 * Strings are English on purpose: the report is meant to be pasted into commits/PRs. UI labels
 * around it are localised in the VS Code layer.
 */

export interface ReportOptions {
  folderName: string;
  now?: Date;
  /** Pro-only sections (validations, secrets) are appended by the caller when present */
  extraSections?: string[];
}

export function buildReport(session: Session, opts: ReportOptions): string {
  const c = counters(session);
  const now = opts.now ?? new Date();
  const started = new Date(session.startedAt);
  const ended = session.stoppedAt ? new Date(session.stoppedAt) : now;
  const mins = Math.max(0, Math.round((ended.getTime() - started.getTime()) / 60000));
  const lines: string[] = [];
  lines.push(`# ChangeKeeper session report — ${opts.folderName}`);
  lines.push('');
  lines.push(`- Session: \`${session.id}\`${session.agent ? ` · agent: ${session.agent}` : ''}${session.label ? ` · ${session.label}` : ''}`);
  lines.push(`- Started: ${started.toISOString()} · ${session.stoppedAt ? 'stopped' : 'running'} · ${mins} min`);
  lines.push(`- Baseline: ${session.kind === 'git' ? 'git index at session start' : 'folder copy at session start'}`);
  lines.push(`- Files: ${c.files} (${c.added} added, ${c.modified} modified, ${c.deleted} deleted, ${c.renamed} renamed) · critical: ${c.critical}`);
  lines.push(`- Hunks: ${c.hunks} (${c.accepted} accepted, ${c.pending} pending, ${c.discarded} discarded)${archivedTotal(session) ? ` · ${archivedTotal(session)} discarded/accepted hunks no longer visible` : ''}`);
  if (session.restores.length) lines.push(`- Restores: ${session.restores.length}${session.restores.some((r) => r.undone) ? ' (some undone)' : ''}`);
  if (session.burstIgnored) lines.push(`- Burst guard: ${session.burstIgnored} new files ignored on request`);
  if (session.notes?.includes('max-files')) lines.push(`- Note: the per-session file cap was reached; some later files were not tracked`);
  lines.push('');
  const files = Object.values(session.changes).sort(sortFiles);
  const critical = files.filter((f) => f.critical);
  if (critical.length) {
    lines.push('## Critical files touched');
    lines.push('');
    for (const f of critical) lines.push(`- ${mark(f)} \`${f.path}\`${f.renamedFrom ? ` (from \`${f.renamedFrom}\`)` : ''} — ${statusOf(f)}`);
    lines.push('');
  }
  lines.push('## Changed files');
  lines.push('');
  if (!files.length) lines.push('_No changes since the baseline._');
  for (const f of files) {
    const hunkIds = Object.keys(f.hunks);
    lines.push(`- ${mark(f)} \`${f.path}\`${f.renamedFrom ? ` (from \`${f.renamedFrom}\`)` : ''} — ${statusOf(f)}${hunkIds.length ? ` · ${hunkIds.length} hunk(s)` : ''}${f.binary ? ' · binary' : ''}${f.tooLarge ? ' · too large' : ''}${f.baselineUnavailable ? ' · no baseline' : ''}${f.baselineUncertain ? ' · baseline uncertain' : ''}`);
    for (const id of hunkIds.sort((a, b) => (f.hunkMeta?.[a]?.newStart ?? 0) - (f.hunkMeta?.[b]?.newStart ?? 0))) {
      const m = f.hunkMeta?.[id];
      lines.push(`  - ${f.hunks[id] === 'accepted' ? '[x]' : f.hunks[id] === 'discarded' ? '[~]' : '[ ]'} ${m ? `\`${m.header}\` (+${m.added} −${m.removed})` : id}`);
    }
  }
  lines.push('');
  for (const s of opts.extraSections ?? []) {
    lines.push(s.trimEnd());
    lines.push('');
  }
  lines.push('## Suggested commit message');
  lines.push('');
  lines.push('```');
  lines.push(suggestCommitMessage(session));
  lines.push('```');
  lines.push('');
  lines.push(`_Generated by ChangeKeeper on ${now.toISOString()}. Local only; nothing was sent anywhere._`);
  return lines.join('\n') + '\n';
}

function archivedTotal(s: Session): number {
  let n = 0;
  for (const f of Object.values(s.changes)) n += (f.archivedAccepted ?? 0) + (f.archivedDiscarded ?? 0);
  return n;
}

function mark(f: FileChange): string {
  return f.kind === 'A' ? '**A**' : f.kind === 'M' ? '**M**' : f.kind === 'D' ? '**D**' : '**R**';
}

function statusOf(f: FileChange): string {
  const ids = Object.keys(f.hunks);
  if (isFileReviewed(f)) return 'reviewed';
  const pending = ids.filter((id) => f.hunks[id] === 'pending').length;
  if (ids.length) return `${pending}/${ids.length} pending`;
  return 'pending';
}

function sortFiles(a: FileChange, b: FileChange): number {
  if (a.critical !== b.critical) return a.critical ? -1 : 1;
  return a.path.localeCompare(b.path);
}

/**
 * Conventional-commit-ish proposal from the paths touched. Type by area, scope by top-level
 * directory when there is one, body listing files. Nothing clever: it is a starting point.
 */
export function suggestCommitMessage(session: Session): string {
  const files = Object.values(session.changes);
  if (!files.length) return 'chore: no changes';
  const paths = files.map((f) => f.path);
  const type = guessType(paths);
  const scope = guessScope(paths);
  const verb = files.every((f) => f.kind === 'A') ? 'add' : files.every((f) => f.kind === 'D') ? 'remove' : 'update';
  const subject = files.length === 1 ? `${verb} ${paths[0]}` : `${verb} ${files.length} files${scope ? ` in ${scope}` : ''}`;
  const head = `${type}${scope && files.length > 1 ? `(${scope})` : ''}: ${subject}`.slice(0, 72);
  const body = files
    .sort(sortFiles)
    .slice(0, 30)
    .map((f) => `- ${f.kind} ${f.path}${f.renamedFrom ? ` (from ${f.renamedFrom})` : ''}`)
    .join('\n');
  const more = files.length > 30 ? `\n- … and ${files.length - 30} more` : '';
  return `${head}\n\n${body}${more}`;
}

function guessType(paths: string[]): string {
  const p = paths.map((x) => x.toLowerCase());
  const all = (re: RegExp) => p.every((x) => re.test(x));
  const any = (re: RegExp) => p.some((x) => re.test(x));
  if (all(/(^|\/)(test|tests|__tests__|spec)\//) || all(/\.(test|spec)\.[a-z]+$/)) return 'test';
  if (all(/\.(md|mdx|rst|txt)$/) || all(/(^|\/)docs?\//)) return 'docs';
  if (all(/(^|\/)(\.github|\.gitlab-ci\.yml|dockerfile|docker-compose|\.circleci)/) || all(/\.(ya?ml)$/)) return 'ci';
  if (all(/(package(-lock)?\.json|pnpm-lock\.yaml|yarn\.lock|requirements.*\.txt|pyproject\.toml|cargo\.(toml|lock)|go\.(mod|sum))$/)) return 'build';
  if (any(/(^|\/)(migrations?|migrate)\//) || any(/\.sql$/)) return 'feat';
  if (any(/(fix|bug|patch)/)) return 'fix';
  return 'feat';
}

function guessScope(paths: string[]): string | undefined {
  const tops = new Set<string>();
  for (const p of paths) {
    const parts = p.split('/');
    if (parts.length > 1) tops.add(parts[0]);
  }
  if (tops.size === 1) return [...tops][0];
  return undefined;
}
